services:
  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8888:8080

  lowkey-vault:
    container_name: lowkey-vault
    image: nagyesta/lowkey-vault:2.8.0
    ports:
      - "8443:8443" # ports for KV
      - "8080:8080" # ports for Managed Id
    volumes:
      - ./.lowkey-vault/import:/import/:rw
    environment:
      LOWKEY_ARGS: >
        --LOWKEY_VAULT_NAMES=- 
        --LOWKEY_DEBUG_REQUEST_LOG=true 
        --LOWKEY_IMPORT_LOCATION=/import/keyvault.json.hbs 
        --LOWKEY_IMPORT_TEMPLATE_HOST=localhost 
        --LOWKEY_IMPORT_TEMPLATE_PORT=8443